# Generated by vcd_resource_list - 2025-03-15T16:43:01+01:00
# Import directive for vcd_vm aat-101-iaas-terraform-tests.aat-101-iaas-terraform-tests.AAT10110276 
import {
  to = vcd_vm.AAT10110276-a31a6d10adbf
  id = "aat-101-iaas-terraform-tests.aat-101-iaas-terraform-tests.urn:vcloud:vm:80706ca7-d1e5-4f27-ada6-a31a6d10adbf"
}

