# Generated by vcd_resource_list - 2025-03-15T16:42:01+01:00
# Import directive for vcd_vm aat-101-iaas-terraform-tests.aat-101-iaas-terraform-tests.AAT10110275 
import {
  to = vcd_vm.AAT10110275-eee4b8ae69ad
  id = "aat-101-iaas-terraform-tests.aat-101-iaas-terraform-tests.urn:vcloud:vm:fae55fac-a976-400a-9bb5-eee4b8ae69ad"
}

