# Generated by vcd_resource_list - 2025-03-15T16:42:30+01:00
# Import directive for vcd_vm aat-101-iaas-terraform-tests.aat-101-iaas-terraform-tests.AAT10110277 
import {
  to = vcd_vm.AAT10110277-234c5ff3e4e5
  id = "aat-101-iaas-terraform-tests.aat-101-iaas-terraform-tests.urn:vcloud:vm:069fdd5a-3658-4923-b073-234c5ff3e4e5"
}

